### ISSUE TITLE
It borked my system, so something's broken in nuget/this extension

### ISSUE THREAD

**Issue by FransBouma** [terrajobst/dotnet-nuget-gc#5] opened 2018-10-25 09:51 UTC
Hi,

I installed this tool, and ran it without an argument. It happily removed all nuget packages from the cache, 10GB cleared. Great!

Well, I then started a build of a multi-targeting sln (netstandard20+net452) and things went wrong: it couldn't find the core .NET base types like Object etc. I tried this: https://github.com/dotnet/core/issues/1006#issuecomment-334906351. This didn't work on the command line, but when I loaded the sln in vs2017 it did compile all of a sudden. Other solutions still didn't compile (which is odd to begin with). I repaired VS2017, uninstalled all .NET core sdk's / runtimes and reinstalled the latest (2.1.403), but still projects failed to build with the simple errors that it can't find System.Object etc. 

So in any case, something's wrong inside nuget/.net core sdk or this extension, I have no idea, but after hours of fighting this, I can't waste any more time on this so I moved back to a backup of my VM. 

Can I stress again that Microsoft has a serious tooling problem? I do appreciate the energy put into tools like this one and others, to help us devs out but it's trying to mitigate a bigger problem and that's reliable solid tooling. Yesterday I installed a brand new VM (win10 1809) with sdk/vs etc. and the first code I pulled from sourcecontrol and tried to build failed because "Microsoft.NET.SDK" wasn't found. An old, still open(!) and forgotten issue about this gave some pointers and repairing vs2017 by installing a workload (even tho I didn't need it) 'fixed it' but it's a sign, like also with this tooling, that something else is broken, but it's unclear what. 

I know this bugreport has no real value other than a sign that 'use it at your own risk!' but not mentioning it here might MS think things are rosy, which sadly they aren't. Hopefully you all fix things soon :)

**Comment by svick** [comment] 2018-10-25 13:02
I can confirm that this happened to me too. Deleting the whole `.nuget` directory seems to fix the issue.

**Comment by FransBouma** [comment] 2018-10-25 13:14
> 
> 
> I can confirm that this happened to me too. Deleting the whole `.nuget` directory seems to fix the issue.

Wished I had that idea before wasting all that time! :smile: In my quest to find the root cause I found many different threads with as much 'solutions' to fix it (or parts of it) so in the end I simply copied back the backup (took an hour, but everything works again). 

Would be interesting to know why removing some nuget cache fails to make csc to find any assemblies.

**Comment by svick** [comment] 2018-10-25 14:39
Turns out that even deleting the directory didn't fix all the issues.

Edit: Though it seems `dotnet clean` helps.

**Comment by FransBouma** [comment] 2018-10-25 18:31
> 
> 
> Turns out that even deleting the directory didn't fix all the issues.
> 
> Edit: Though it seems `dotnet clean` helps.

Interesting :) I tried that too and it didn't help! Clearly something weird is going on...

**Comment by terrajobst** [comment] 2018-10-25 22:10
Normally, I'll try `git clean -xdf` (on a clean working copy obviously) to remove all the bin/obj folders. Package restore checks whether the `assets.json` file in `obj` is up-to-date with respect to the .csproj file; I don't think it checks whether the cache is still valid. So you might have to force package restore again. `dotnet restore -f` should work, too.

**Comment by terrajobst** [comment] 2018-10-25 23:47
I don't think there is anything this tool can do differently here. Also, I've tried to delete random folders by hand, but `dotnet restore` seems to put them back. I'm closing this for now.

Please re-open if anyone gets a repro!

**Closed as completed** 2018-10-25 23:48 UTC
